theme: jekyll-theme-cayman
title: Apply Machine Learning to Identify Causes of Poverty
description:Thomas Yang, Yibo Pan, EECS349 Machine Learning, Professor Doug Downey, Northwestern University
show_downloads: true
